/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        lq: {
          primary: 'var(--lq-primary)',
          'primary-hover': 'var(--lq-primary-hover)',
          'primary-depth': 'var(--lq-primary-depth)',
          secondary: 'var(--lq-secondary)',
          'secondary-hover': 'var(--lq-secondary-hover)',
          'secondary-depth': 'var(--lq-secondary-depth)',
          success: 'var(--lq-success)',
          'success-hover': 'var(--lq-success-hover)',
          'success-depth': 'var(--lq-success-depth)',
          'success-bg': 'var(--lq-success-bg)',
          error: 'var(--lq-error)',
          'error-hover': 'var(--lq-error-hover)',
          'error-depth': 'var(--lq-error-depth)',
          'error-bg': 'var(--lq-error-bg)',
          warning: 'var(--lq-warning)',
          'warning-depth': 'var(--lq-warning-depth)',
          'bg-page': 'var(--lq-bg-page)',
          'bg-surface': 'var(--lq-bg-surface)',
          'bg-elevated': 'var(--lq-bg-elevated)',
          'bg-sunken': 'var(--lq-bg-sunken)',
          'text-primary': 'var(--lq-text-primary)',
          'text-secondary': 'var(--lq-text-secondary)',
          'text-disabled': 'var(--lq-text-disabled)',
          'text-inverse': 'var(--lq-text-inverse)',
          'text-success': 'var(--lq-text-success)',
          'text-error': 'var(--lq-text-error)',
          'border-default': 'var(--lq-border-default)',
          'border-strong': 'var(--lq-border-strong)',
          'border-focus': 'var(--lq-border-focus)',
          'border-divider': 'var(--lq-border-divider)',
          xp: 'var(--lq-xp-color)',
          'xp-bg': 'var(--lq-xp-bg)',
          streak: 'var(--lq-streak-color)',
          'streak-bg': 'var(--lq-streak-bg)',
          heart: 'var(--lq-heart-color)',
          'heart-bg': 'var(--lq-heart-bg)',
          gem: 'var(--lq-gem-color)',
          crown: 'var(--lq-crown-color)',
          'crown-bg': 'var(--lq-crown-bg)',
          timed: 'var(--lq-timed-color)',
          'timed-critical': 'var(--lq-timed-critical)',
          'timed-warning': 'var(--lq-timed-warning)',
          'locked-bg': 'var(--lq-locked-bg)',
          'locked-border': 'var(--lq-locked-border)',
          'locked-text': 'var(--lq-locked-text)',
          'available-bg': 'var(--lq-available-bg)',
          'available-border': 'var(--lq-available-border)',
          'active-ring': 'var(--lq-active-ring)',
          'selected-bg': 'var(--lq-selected-bg)',
          'selected-border': 'var(--lq-selected-border)',
        },
      },
      borderRadius: {
        lq: 'var(--lq-radius-md)',
        'lq-sm': 'var(--lq-radius-sm)',
        'lq-lg': 'var(--lq-radius-lg)',
        'lq-xl': 'var(--lq-radius-xl)',
        'lq-full': 'var(--lq-radius-full)',
      },
      boxShadow: {
        'lq-sm': 'var(--lq-shadow-sm)',
        'lq-md': 'var(--lq-shadow-md)',
        'lq-lg': 'var(--lq-shadow-lg)',
        'lq-xl': 'var(--lq-shadow-xl)',
        'lq-inner': 'var(--lq-shadow-inner)',
        'lq-focus': 'var(--lq-focus-ring)',
      },
      maxWidth: {
        'lq-narrow': 'var(--lq-content-narrow)',
        'lq-standard': 'var(--lq-content-standard)',
        'lq-wide': 'var(--lq-content-wide)',
        'lq-full': 'var(--lq-content-full)',
      },
      zIndex: {
        sticky: 'var(--lq-z-sticky)',
        navigation: 'var(--lq-z-navigation)',
        dropdown: 'var(--lq-z-dropdown)',
        feedback: 'var(--lq-z-feedback)',
        modal: 'var(--lq-z-modal)',
        toast: 'var(--lq-z-toast)',
        tooltip: 'var(--lq-z-tooltip)',
      },
      fontFamily: {
        sans: ["'Nunito Variable'", "'Nunito'", 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontWeight: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
      },
      fontSize: {
        'lq-xs': ['0.75rem', { lineHeight: '1rem' }],
        'lq-sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'lq-base': ['1rem', { lineHeight: '1.5rem' }],
        'lq-lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'lq-xl': ['1.25rem', { lineHeight: '1.75rem' }],
        'lq-2xl': ['1.5rem', { lineHeight: '2rem' }],
        'lq-3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        'lq-4xl': ['2.25rem', { lineHeight: '2.5rem' }],
      },
    },
  },
  plugins: [],
}
