"""Mako template for migration scripts."""

"""initial schema with all tables constraints and indexes

Revision ID: ca24b65a41a3
Revises: 
Create Date: 2026-07-18 17:05:39.555549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca24b65a41a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('criteria_type', sa.String(), nullable=False),
    sa.Column('criteria_value', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("criteria_type IN ('streak_days', 'total_xp', 'skills_completed', 'perfect_lessons')", name=op.f('ck_achievements_ck_achievements_criteria_type_valid')),
    sa.CheckConstraint('criteria_value > 0', name=op.f('ck_achievements_ck_achievements_criteria_value_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements'))
    )
    op.create_index(op.f('ix_achievements_key'), 'achievements', ['key'], unique=True)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('from_language_code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('language_code', 'from_language_code', name='uq_courses_language_pair')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('hearts', sa.Integer(), nullable=False),
    sa.Column('max_hearts', sa.Integer(), nullable=False),
    sa.Column('heart_regen_anchor_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gems', sa.Integer(), nullable=False),
    sa.Column('daily_goal_xp', sa.Integer(), nullable=False),
    sa.Column('active_course_id', sa.Integer(), nullable=True),
    sa.Column('is_content_admin', sa.Boolean(), nullable=False),
    sa.CheckConstraint('current_streak >= 0', name=op.f('ck_users_ck_users_current_streak_positive')),
    sa.CheckConstraint('daily_goal_xp > 0', name=op.f('ck_users_ck_users_daily_goal_positive')),
    sa.CheckConstraint('gems >= 0', name=op.f('ck_users_ck_users_gems_positive')),
    sa.CheckConstraint('hearts >= 0 AND hearts <= max_hearts', name=op.f('ck_users_ck_users_hearts_valid')),
    sa.CheckConstraint('longest_streak >= current_streak', name=op.f('ck_users_ck_users_longest_streak_valid')),
    sa.CheckConstraint('max_hearts > 0', name=op.f('ck_users_ck_users_max_hearts_positive')),
    sa.CheckConstraint('total_xp >= 0', name=op.f('ck_users_ck_users_total_xp_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('color_theme', sa.String(), nullable=False),
    sa.CheckConstraint('order_index >= 0', name=op.f('ck_units_ck_units_order_positive')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_units_course_id_courses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units')),
    sa.UniqueConstraint('course_id', 'order_index', name='uq_units_course_order')
    )
    op.create_index('ix_units_course_order', 'units', ['course_id', 'order_index'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name=op.f('fk_user_achievements_achievement_id_achievements'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_achievements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_achievements')),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievements_user_achievement')
    )
    op.create_index('ix_user_achievements_earned', 'user_achievements', ['user_id', 'earned_at'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('unlock_requires_skill_id', sa.Integer(), nullable=True),
    sa.Column('max_level', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_level > 0', name=op.f('ck_skills_ck_skills_max_level_positive')),
    sa.CheckConstraint('order_index >= 0', name=op.f('ck_skills_ck_skills_order_positive')),
    sa.CheckConstraint('unlock_requires_skill_id IS NULL OR unlock_requires_skill_id != id', name=op.f('ck_skills_ck_skills_no_self_prerequisite')),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_skills_unit_id_units'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unlock_requires_skill_id'], ['skills.id'], name=op.f('fk_skills_unlock_requires_skill_id_skills'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('unit_id', 'order_index', name='uq_skills_unit_order')
    )
    op.create_index('ix_skills_prerequisite', 'skills', ['unlock_requires_skill_id'], unique=False)
    op.create_index('ix_skills_unit_order', 'skills', ['unit_id', 'order_index'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.CheckConstraint('order_index >= 0', name=op.f('ck_lessons_ck_lessons_order_positive')),
    sa.CheckConstraint('xp_reward > 0', name=op.f('ck_lessons_ck_lessons_xp_positive')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_lessons_skill_id_skills'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons')),
    sa.UniqueConstraint('skill_id', 'order_index', name='uq_lessons_skill_order')
    )
    op.create_index('ix_lessons_skill_order', 'lessons', ['skill_id', 'order_index'], unique=False)
    op.create_table('user_skill_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('crowns', sa.Integer(), nullable=False),
    sa.Column('times_practiced', sa.Integer(), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('crowns >= 0', name=op.f('ck_user_skill_progress_ck_user_skill_progress_crowns_positive')),
    sa.CheckConstraint('times_practiced >= 0', name=op.f('ck_user_skill_progress_ck_user_skill_progress_practiced_positive')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_user_skill_progress_skill_id_skills'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_skill_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_skill_progress')),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_user_skill_progress_user_skill')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type IN ('multiple_choice', 'translate_word_bank', 'match_pairs', 'fill_blank', 'type_answer')", name=op.f('ck_exercises_ck_exercises_type_valid')),
    sa.CheckConstraint('order_index >= 0', name=op.f('ck_exercises_ck_exercises_order_positive')),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_exercises_lesson_id_lessons'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises')),
    sa.UniqueConstraint('lesson_id', 'order_index', name='uq_exercises_lesson_order')
    )
    op.create_index('ix_exercises_lesson_active', 'exercises', ['lesson_id', 'is_active'], unique=False)
    op.create_index('ix_exercises_type', 'exercises', ['type'], unique=False)
    op.create_table('lesson_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activity_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('exercise_order', sa.JSON(), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('mistakes_count', sa.Integer(), nullable=False),
    sa.Column('hearts_lost', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('in_progress', 'completed', 'failed')", name=op.f('ck_lesson_attempts_ck_lesson_attempts_status_valid')),
    sa.CheckConstraint('current_index >= 0', name=op.f('ck_lesson_attempts_ck_lesson_attempts_index_positive')),
    sa.CheckConstraint('hearts_lost >= 0', name=op.f('ck_lesson_attempts_ck_lesson_attempts_hearts_lost_positive')),
    sa.CheckConstraint('mistakes_count >= 0', name=op.f('ck_lesson_attempts_ck_lesson_attempts_mistakes_positive')),
    sa.CheckConstraint('xp_earned IS NULL OR xp_earned >= 0', name=op.f('ck_lesson_attempts_ck_lesson_attempts_xp_positive')),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_attempts_lesson_id_lessons'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lesson_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_attempts'))
    )
    op.create_index('ix_attempts_lesson_status', 'lesson_attempts', ['lesson_id', 'status'], unique=False)
    op.create_index('ix_attempts_user_activity', 'lesson_attempts', ['user_id', 'activity_date', 'status'], unique=False)
    op.create_index('ix_attempts_user_completed', 'lesson_attempts', ['user_id', 'completed_at'], unique=False)
    op.create_index('ix_attempts_user_status', 'lesson_attempts', ['user_id', 'status'], unique=False)
    op.create_table('exercise_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_attempt_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('exercise_type', sa.String(), nullable=False),
    sa.Column('submitted_answer', sa.JSON(), nullable=False),
    sa.Column('correct_answer_snapshot', sa.JSON(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("exercise_type IN ('multiple_choice', 'translate_word_bank', 'match_pairs', 'fill_blank', 'type_answer')", name=op.f('ck_exercise_answers_ck_exercise_answers_type_valid')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_exercise_answers_ck_exercise_answers_position_positive')),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercise_answers_exercise_id_exercises'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lesson_attempt_id'], ['lesson_attempts.id'], name=op.f('fk_exercise_answers_lesson_attempt_id_lesson_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_answers')),
    sa.UniqueConstraint('lesson_attempt_id', 'exercise_id', name='uq_exercise_answers_attempt_exercise'),
    sa.UniqueConstraint('lesson_attempt_id', 'position', name='uq_exercise_answers_attempt_position')
    )
    op.create_index('ix_answers_exercise', 'exercise_answers', ['exercise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_answers_exercise', table_name='exercise_answers')
    op.drop_table('exercise_answers')
    op.drop_index('ix_attempts_user_status', table_name='lesson_attempts')
    op.drop_index('ix_attempts_user_completed', table_name='lesson_attempts')
    op.drop_index('ix_attempts_user_activity', table_name='lesson_attempts')
    op.drop_index('ix_attempts_lesson_status', table_name='lesson_attempts')
    op.drop_table('lesson_attempts')
    op.drop_index('ix_exercises_type', table_name='exercises')
    op.drop_index('ix_exercises_lesson_active', table_name='exercises')
    op.drop_table('exercises')
    op.drop_table('user_skill_progress')
    op.drop_index('ix_lessons_skill_order', table_name='lessons')
    op.drop_table('lessons')
    op.drop_index('ix_skills_unit_order', table_name='skills')
    op.drop_index('ix_skills_prerequisite', table_name='skills')
    op.drop_table('skills')
    op.drop_index('ix_user_achievements_earned', table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index('ix_units_course_order', table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('courses')
    op.drop_index(op.f('ix_achievements_key'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
